"""
backend/app.py
Flask REST API for Vimana Wars Online Leaderboard.
Uses SQLite for zero-config persistence.
"""
import sqlite3
import os
import logging
import hashlib
import hmac
import json
import re
import secrets
import threading
import time
from collections import defaultdict, deque
from pathlib import Path
from flask import Flask, request, jsonify

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
logger = logging.getLogger("VimanaWarsBackend")

app = Flask(__name__)

DB_PATH = Path(os.environ.get("DATABASE_PATH", "leaderboard.db"))
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()
SESSION_TTL_SECONDS = 30 * 24 * 60 * 60
ACTION_TOKEN_TTL_SECONDS = 30 * 60
REQUIRE_EMAIL_VERIFICATION = os.environ.get("REQUIRE_EMAIL_VERIFICATION", "0").lower() in ("1", "true", "yes")
SHOW_DEV_AUTH_TOKENS = os.environ.get("SHOW_DEV_AUTH_TOKENS", "0").lower() in ("1", "true", "yes")
_EMAIL_RE = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
_SHIP_IDS = (
    "pushpaka", "tripura", "garuda", "vajra", "naga",
    "agneyastra", "soma", "kubera", "surya",
)
_RATE_LIMITS = {
    "register": (5, 60),
    "login": (10, 60),
    "verify": (10, 60),
    "reset_request": (5, 60),
    "reset_password": (10, 60),
    "score": (60, 60),
}
_rate_state = defaultdict(deque)
_rate_lock = threading.Lock()
_PROFILE_KEYS = {
    "player_name", "high_score", "last_wave", "difficulty", "last_ship",
    "last_realm", "realm_unlock_seen", "total_kills", "games_played",
    "total_damage", "best_combo", "total_boons", "bosses_defeated",
    "playtime_seconds", "ships_mastered", "achievements", "endless_high_wave",
    "endless_high_score",
}


def get_db():
    if DATABASE_URL:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as exc:
            raise RuntimeError("DATABASE_URL is set but psycopg is not installed") from exc
        connection = psycopg.connect(DATABASE_URL, row_factory=dict_row)
        return _PostgresConnection(connection)
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


class _PostgresConnection:
    """Tiny compatibility wrapper for the existing parameterized queries."""
    is_postgres = True

    def __init__(self, connection):
        self._connection = connection

    def execute(self, statement, params=()):
        return self._connection.execute(statement.replace("?", "%s"), params)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        if exc_type:
            self.rollback()
        else:
            self.commit()
        self._connection.close()


def _is_postgres() -> bool:
    return bool(DATABASE_URL)


def init_db():
    with get_db() as conn:
        id_definition = (
            "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            if _is_postgres() else "INTEGER PRIMARY KEY AUTOINCREMENT"
        )
        conn.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id %s,
                game_id TEXT NOT NULL UNIQUE,
                email TEXT NOT NULL UNIQUE COLLATE NOCASE,
                player_name TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                email_verified INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """ % id_definition)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS sessions (
                token_hash TEXT PRIMARY KEY,
                user_id INTEGER NOT NULL,
                expires_at INTEGER NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS auth_tokens (
                token_hash TEXT PRIMARY KEY,
                user_id INTEGER NOT NULL,
                purpose TEXT NOT NULL,
                expires_at INTEGER NOT NULL,
                consumed_at INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS profiles (
                user_id INTEGER PRIMARY KEY,
                profile_json TEXT NOT NULL DEFAULT '{}',
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS scores (
                id %s,
                player_name TEXT NOT NULL,
                score INTEGER NOT NULL,
                level_reached INTEGER NOT NULL,
                difficulty TEXT DEFAULT 'normal',
                ship_class TEXT DEFAULT 'pushpaka',
                user_id INTEGER,
                game_id TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """ % id_definition)
        # Safe migrations for databases created by earlier versions.
        for statement in (
            "ALTER TABLE users ADD COLUMN email_verified INTEGER NOT NULL DEFAULT 0",
            "ALTER TABLE scores ADD COLUMN ship_class TEXT DEFAULT 'pushpaka'",
            "ALTER TABLE scores ADD COLUMN user_id INTEGER",
            "ALTER TABLE scores ADD COLUMN game_id TEXT",
            "ALTER TABLE scores ADD COLUMN kills INTEGER DEFAULT 0",
            "ALTER TABLE scores ADD COLUMN total_damage INTEGER DEFAULT 0",
            "ALTER TABLE scores ADD COLUMN duration_seconds REAL DEFAULT 0",
        ):
            try:
                conn.execute(statement)
            except Exception as exc:
                # SQLite and PostgreSQL both report duplicate columns here;
                # preserve real connection/schema errors.
                duplicate_column = (
                    isinstance(exc, sqlite3.OperationalError)
                    or (_is_postgres() and getattr(exc, "sqlstate", None) == "42701")
                )
                if not duplicate_column:
                    raise
        conn.commit()


# Initialize database table on startup
init_db()


@app.route("/", methods=["GET"])
def index():
    logger.info("API Root status checked from %s", request.remote_addr)
    return jsonify({
        "game": "Vimana Wars API",
        "status": "online",
        "endpoints": {
            "GET /scores/top": "Get top leaderboard entries (?limit=10&difficulty=normal)",
            "POST /scores": "Submit a score (Bearer token optional for guest submissions)",
            "POST /auth/register": "Create an email account and receive a stable Game ID",
            "POST /auth/login": "Sign in with email and password",
            "POST /auth/verify-email": "Verify an email address with its one-time token",
            "POST /auth/request-password-reset": "Request a password reset token",
            "POST /auth/reset-password": "Set a new password with a reset token",
            "GET /auth/me": "Get the signed-in player profile",
            "GET /account/profile": "Get cloud-synced progression and achievements",
            "PUT /account/profile": "Sync cloud-saved progression and achievements",
            "GET /account/stats": "Get personal online gameplay statistics",
            "GET /scores/stats": "Global gameplay metrics",
        }
    })


def _rate_limit(action: str):
    """Small process-local guard; production deployments should use Redis."""
    limit, window = _RATE_LIMITS[action]
    now = time.monotonic()
    key = (action, request.remote_addr or "unknown")
    with _rate_lock:
        calls = _rate_state[key]
        while calls and now - calls[0] >= window:
            calls.popleft()
        if len(calls) >= limit:
            retry_after = max(1, int(window - (now - calls[0])))
            return jsonify({"error": "Too many requests. Please try again shortly."}), 429, {
                "Retry-After": str(retry_after)
            }
        calls.append(now)
    return None


def _new_action_token(conn, user_id: int, purpose: str) -> str:
    token = secrets.token_urlsafe(32)
    conn.execute(
        "INSERT INTO auth_tokens (token_hash, user_id, purpose, expires_at) VALUES (?, ?, ?, ?)",
        (hashlib.sha256(token.encode("utf-8")).hexdigest(), user_id, purpose,
         int(time.time()) + ACTION_TOKEN_TTL_SECONDS),
    )
    return token


def _default_profile() -> dict:
    return {
        "player_name": "Warrior", "high_score": 0, "last_wave": 0,
        "difficulty": "normal", "last_ship": "pushpaka", "last_realm": 1,
        "realm_unlock_seen": [], "total_kills": 0, "games_played": 0,
        "total_damage": 0, "best_combo": 1, "total_boons": 0,
        "bosses_defeated": [], "playtime_seconds": 0, "ships_mastered": [],
        "achievements": [], "endless_high_wave": 0, "endless_high_score": 0,
    }


def _profile_from_payload(value) -> dict:
    if not isinstance(value, dict):
        return {}
    profile = {}
    for key in _PROFILE_KEYS:
        if key in value:
            profile[key] = value[key]
    # Prevent a malformed client from creating unbounded profile data.
    encoded = json.dumps(profile, separators=(",", ":"))
    return profile if len(encoded) <= 100_000 else {}


def _password_hash(password: str) -> str:
    salt = secrets.token_bytes(16)
    digest = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, 210_000)
    return f"pbkdf2_sha256$210000${salt.hex()}${digest.hex()}"


def _password_matches(password: str, encoded: str) -> bool:
    try:
        algorithm, rounds, salt_hex, digest_hex = encoded.split("$", 3)
        if algorithm != "pbkdf2_sha256":
            return False
        expected = hashlib.pbkdf2_hmac(
            "sha256", password.encode("utf-8"), bytes.fromhex(salt_hex), int(rounds)
        ).hex()
        return hmac.compare_digest(expected, digest_hex)
    except (TypeError, ValueError):
        return False


def _new_game_id(conn) -> str:
    while True:
        game_id = f"VMN-{secrets.token_hex(4).upper()}"
        if conn.execute("SELECT 1 FROM users WHERE game_id = ?", (game_id,)).fetchone() is None:
            return game_id


def _user_payload(row) -> dict:
    return {
        "game_id": row["game_id"],
        "email": row["email"],
        "player_name": row["player_name"],
        "email_verified": bool(row["email_verified"]) if "email_verified" in row.keys() else False,
    }


def _current_user():
    """Resolve an opaque bearer token without exposing password data."""
    header = request.headers.get("Authorization", "")
    if not header.lower().startswith("bearer "):
        return None
    token = header[7:].strip()
    if not token:
        return None
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    now = int(time.time())
    with get_db() as conn:
        row = conn.execute(
            """
            SELECT u.id, u.game_id, u.email, u.player_name, u.email_verified
            FROM sessions s JOIN users u ON u.id = s.user_id
            WHERE s.token_hash = ? AND s.expires_at > ?
            """, (token_hash, now)
        ).fetchone()
    return row


@app.route("/auth/register", methods=["POST"])
def register():
    limited = _rate_limit("register")
    if limited:
        return limited
    data = request.get_json(silent=True) or {}
    email = str(data.get("email", "")).strip().lower()
    password = str(data.get("password", ""))
    player_name = str(data.get("player_name", "Warrior")).strip()[:20] or "Warrior"
    if not _EMAIL_RE.match(email) or len(email) > 254:
        return jsonify({"error": "Enter a valid email address"}), 400
    if len(password) < 8 or len(password) > 128:
        return jsonify({"error": "Password must be 8 to 128 characters"}), 400

    token = secrets.token_urlsafe(32)
    token_hash = hashlib.sha256(token.encode("utf-8")).hexdigest()
    with get_db() as conn:
        try:
            game_id = _new_game_id(conn)
            cursor = conn.execute(
                """
                INSERT INTO users (game_id, email, player_name, password_hash, email_verified)
                VALUES (?, ?, ?, ?, ?)
                """, (game_id, email, player_name, _password_hash(password),
                      0 if REQUIRE_EMAIL_VERIFICATION else 1)
            )
            user_id = cursor.lastrowid
            verification_token = _new_action_token(conn, user_id, "verify_email")
            conn.execute(
                "INSERT INTO profiles (user_id, profile_json) VALUES (?, ?)",
                (user_id, json.dumps(_default_profile(), separators=(",", ":"))),
            )
            session_token = None
            if not REQUIRE_EMAIL_VERIFICATION:
                session_token = token
            else:
                # A new account must verify its email before a session is issued.
                token = None
            if session_token:
                conn.execute(
                    "INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, ?)",
                    (token_hash, user_id, int(time.time()) + SESSION_TTL_SECONDS)
                )
            row = conn.execute(
                "SELECT game_id, email, player_name, email_verified FROM users WHERE id = ?", (user_id,)
            ).fetchone()
            conn.commit()
        except sqlite3.IntegrityError:
            return jsonify({"error": "An account with that email already exists"}), 409
    response = {
        "success": True,
        "token": token,
        "verification_required": REQUIRE_EMAIL_VERIFICATION,
        "user": _user_payload(row),
    }
    if REQUIRE_EMAIL_VERIFICATION and SHOW_DEV_AUTH_TOKENS:
        response["verification_token"] = verification_token
    return jsonify(response), 201


@app.route("/auth/login", methods=["POST"])
def login():
    limited = _rate_limit("login")
    if limited:
        return limited
    data = request.get_json(silent=True) or {}
    email = str(data.get("email", "")).strip().lower()
    password = str(data.get("password", ""))
    with get_db() as conn:
        row = conn.execute(
            "SELECT id, game_id, email, player_name, password_hash, email_verified FROM users WHERE email = ?",
            (email,)
        ).fetchone()
        if row is None or not _password_matches(password, row["password_hash"]):
            return jsonify({"error": "Email or password is incorrect"}), 401
        if REQUIRE_EMAIL_VERIFICATION and not row["email_verified"]:
            return jsonify({
                "error": "Please verify your email before signing in",
                "verification_required": True,
            }), 403
        token = secrets.token_urlsafe(32)
        conn.execute(
            "INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, ?)",
            (hashlib.sha256(token.encode("utf-8")).hexdigest(), row["id"], int(time.time()) + SESSION_TTL_SECONDS)
        )
        conn.commit()
    return jsonify({"success": True, "token": token, "user": _user_payload(row)}), 200


@app.route("/auth/me", methods=["GET"])
def me():
    user = _current_user()
    if user is None:
        return jsonify({"error": "Authentication required"}), 401
    return jsonify({"user": _user_payload(user)})


@app.route("/auth/verify-email", methods=["POST"])
def verify_email():
    limited = _rate_limit("verify")
    if limited:
        return limited
    data = request.get_json(silent=True) or {}
    raw_token = str(data.get("token", "")).strip()
    if not raw_token:
        return jsonify({"error": "Verification token is required"}), 400
    token_hash = hashlib.sha256(raw_token.encode("utf-8")).hexdigest()
    now = int(time.time())
    with get_db() as conn:
        row = conn.execute(
            """
            SELECT u.id, u.game_id, u.email, u.player_name, u.email_verified
            FROM auth_tokens t JOIN users u ON u.id = t.user_id
            WHERE t.token_hash = ? AND t.purpose = 'verify_email'
              AND t.consumed_at IS NULL AND t.expires_at > ?
            """, (token_hash, now)
        ).fetchone()
        if row is None:
            return jsonify({"error": "Verification token is invalid or expired"}), 400
        conn.execute("UPDATE users SET email_verified = 1 WHERE id = ?", (row["id"],))
        conn.execute("UPDATE auth_tokens SET consumed_at = ? WHERE token_hash = ?", (now, token_hash))
        session_token = secrets.token_urlsafe(32)
        conn.execute(
            "INSERT INTO sessions (token_hash, user_id, expires_at) VALUES (?, ?, ?)",
            (hashlib.sha256(session_token.encode("utf-8")).hexdigest(), row["id"], now + SESSION_TTL_SECONDS),
        )
        conn.commit()
    return jsonify({"success": True, "token": session_token,
                    "user": {**_user_payload(row), "email_verified": True}})


@app.route("/auth/request-password-reset", methods=["POST"])
def request_password_reset():
    limited = _rate_limit("reset_request")
    if limited:
        return limited
    data = request.get_json(silent=True) or {}
    email = str(data.get("email", "")).strip().lower()
    response = {"success": True, "message": "If that email exists, reset instructions have been created."}
    with get_db() as conn:
        row = conn.execute("SELECT id FROM users WHERE email = ?", (email,)).fetchone()
        if row is not None:
            reset_token = _new_action_token(conn, row["id"], "reset_password")
            conn.commit()
            if SHOW_DEV_AUTH_TOKENS:
                response["reset_token"] = reset_token
    return jsonify(response)


@app.route("/auth/reset-password", methods=["POST"])
def reset_password():
    limited = _rate_limit("reset_password")
    if limited:
        return limited
    data = request.get_json(silent=True) or {}
    raw_token = str(data.get("token", "")).strip()
    password = str(data.get("password", ""))
    if len(password) < 8 or len(password) > 128:
        return jsonify({"error": "Password must be 8 to 128 characters"}), 400
    token_hash = hashlib.sha256(raw_token.encode("utf-8")).hexdigest()
    now = int(time.time())
    with get_db() as conn:
        row = conn.execute(
            """
            SELECT user_id FROM auth_tokens
            WHERE token_hash = ? AND purpose = 'reset_password'
              AND consumed_at IS NULL AND expires_at > ?
            """, (token_hash, now)
        ).fetchone()
        if row is None:
            return jsonify({"error": "Reset token is invalid or expired"}), 400
        conn.execute("UPDATE users SET password_hash = ? WHERE id = ?", (_password_hash(password), row["user_id"]))
        conn.execute("DELETE FROM sessions WHERE user_id = ?", (row["user_id"],))
        conn.execute("UPDATE auth_tokens SET consumed_at = ? WHERE token_hash = ?", (now, token_hash))
        conn.commit()
    return jsonify({"success": True, "message": "Password updated. Please sign in again."})


@app.route("/auth/logout", methods=["POST"])
def logout():
    header = request.headers.get("Authorization", "")
    token = header[7:].strip() if header.lower().startswith("bearer ") else ""
    if token:
        with get_db() as conn:
            conn.execute(
                "DELETE FROM sessions WHERE token_hash = ?",
                (hashlib.sha256(token.encode("utf-8")).hexdigest(),)
            )
            conn.commit()
    return jsonify({"success": True})


def _require_user():
    user = _current_user()
    if user is None:
        return None, (jsonify({"error": "Authentication required"}), 401)
    return user, None


@app.route("/account/profile", methods=["GET"])
def get_profile():
    user, error = _require_user()
    if error:
        return error
    with get_db() as conn:
        row = conn.execute("SELECT profile_json, updated_at FROM profiles WHERE user_id = ?", (user["id"],)).fetchone()
    try:
        profile = json.loads(row["profile_json"]) if row else _default_profile()
    except (TypeError, ValueError):
        profile = _default_profile()
    return jsonify({"profile": profile, "updated_at": row["updated_at"] if row else None})


@app.route("/account/profile", methods=["PUT"])
def update_profile():
    user, error = _require_user()
    if error:
        return error
    data = request.get_json(silent=True) or {}
    incoming = _profile_from_payload(data.get("profile", data))
    if not incoming:
        return jsonify({"error": "A valid profile object is required"}), 400
    with get_db() as conn:
        row = conn.execute("SELECT profile_json FROM profiles WHERE user_id = ?", (user["id"],)).fetchone()
        try:
            current = json.loads(row["profile_json"]) if row else _default_profile()
        except (TypeError, ValueError):
            current = _default_profile()
        current.update(incoming)
        if "player_name" in current:
            current["player_name"] = str(current["player_name"]).strip()[:20] or "Warrior"
        encoded = json.dumps(current, separators=(",", ":"))
        if len(encoded) > 100_000:
            return jsonify({"error": "Profile is too large"}), 413
        conn.execute(
            """
            INSERT INTO profiles (user_id, profile_json, updated_at) VALUES (?, ?, CURRENT_TIMESTAMP)
            ON CONFLICT(user_id) DO UPDATE SET profile_json = excluded.profile_json,
                                               updated_at = CURRENT_TIMESTAMP
            """, (user["id"], encoded)
        )
        if current.get("player_name"):
            conn.execute("UPDATE users SET player_name = ? WHERE id = ?", (current["player_name"], user["id"]))
        conn.commit()
    return jsonify({"success": True, "profile": current})


@app.route("/account/stats", methods=["GET"])
def get_account_stats():
    user, error = _require_user()
    if error:
        return error
    with get_db() as conn:
        row = conn.execute(
            """
            SELECT COUNT(*) AS games, COALESCE(MAX(score), 0) AS best_score,
                   COALESCE(SUM(score), 0) AS total_score,
                   COALESCE(MAX(level_reached), 0) AS best_wave,
                   COALESCE(SUM(kills), 0) AS total_kills,
                   COALESCE(SUM(total_damage), 0) AS total_damage
            FROM scores WHERE user_id = ?
            """, (user["id"],)
        ).fetchone()
        achievements = conn.execute(
            "SELECT profile_json FROM profiles WHERE user_id = ?", (user["id"],)
        ).fetchone()
    unlocked = 0
    if achievements:
        try:
            unlocked = len(json.loads(achievements["profile_json"]).get("achievements", []))
        except (TypeError, ValueError):
            unlocked = 0
    return jsonify({
        "game_id": user["game_id"], "games": row["games"],
        "best_score": row["best_score"], "total_score": row["total_score"],
        "best_wave": row["best_wave"], "total_kills": row["total_kills"],
        "total_damage": row["total_damage"], "achievements_unlocked": unlocked,
    })


@app.route("/scores", methods=["POST"])
def submit_score():
    limited = _rate_limit("score")
    if limited:
        return limited
    data = request.get_json(silent=True) or {}
    user = _current_user()
    player_name = str(data.get("player_name", "Anonymous")).strip()[:20] or "Anonymous"
    
    try:
        score = int(data.get("score", 0))
        level_reached = int(data.get("level_reached", 1))
        kills = int(data.get("kills", 0))
        total_damage = int(data.get("total_damage", 0))
        duration_seconds = float(data.get("duration_seconds", 0))
    except (ValueError, TypeError):
        logger.warning("Invalid score/level submission from %s: %s", request.remote_addr, data)
        return jsonify({"error": "Invalid score or level format"}), 400

    difficulty = str(data.get("difficulty", "normal")).lower()
    if difficulty not in ("easy", "normal", "hard", "endless"):
        difficulty = "normal"

    ship_class = str(data.get("ship_class", "pushpaka")).lower()
    if ship_class not in _SHIP_IDS:
        ship_class = "pushpaka"

    # These are deliberately generous sanity limits. They stop accidental or
    # obviously forged payloads while leaving room for future balance changes.
    max_wave = 10000 if difficulty == "endless" else 20
    max_score = max(250_000, level_reached * 250_000)
    if level_reached < 1 or level_reached > max_wave:
        return jsonify({"error": "Invalid wave value"}), 422
    if score < 0 or score > max_score or kills < 0 or kills > level_reached * 1000:
        logger.warning("Negative score rejected from %s: %s", request.remote_addr, score)
        return jsonify({"error": "Score failed sanity validation"}), 422
    if total_damage < 0 or duration_seconds < 0 or duration_seconds > 24 * 60 * 60:
        return jsonify({"error": "Run statistics failed sanity validation"}), 422

    with get_db() as conn:
        cursor = conn.execute(
            """
                INSERT INTO scores (player_name, score, level_reached, difficulty, ship_class,
                                    user_id, game_id, kills, total_damage, duration_seconds)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                user["player_name"] if user else player_name,
                score, level_reached, difficulty, ship_class,
                user["id"] if user else None,
                user["game_id"] if user else None,
                kills, total_damage, duration_seconds,
            )
        )
        conn.commit()
        inserted_id = cursor.lastrowid

    stored_name = user["player_name"] if user else player_name
    logger.info(
        "🏆 Score Recorded [ID=%s]: Warrior='%s' | Ship='%s' | Score=%s | Wave=%s | Diff='%s'",
        inserted_id, stored_name, ship_class.upper(), score, level_reached, difficulty.upper()
    )

    return jsonify({
        "success": True,
        "message": "Score recorded successfully",
        "id": inserted_id,
        "player_name": stored_name,
        "game_id": user["game_id"] if user else None,
        "ship_class": ship_class,
        "score": score,
        "level_reached": level_reached,
        "difficulty": difficulty,
        "kills": kills,
        "total_damage": total_damage,
        "duration_seconds": duration_seconds,
    }), 201


@app.route("/scores/top", methods=["GET"])
def get_top_scores():
    try:
        limit = min(max(1, int(request.args.get("limit", 10))), 50)
    except ValueError:
        limit = 10

    difficulty = request.args.get("difficulty")
    logger.info("Fetching leaderboard: limit=%s, difficulty=%s", limit, difficulty)

    with get_db() as conn:
        if difficulty and difficulty in ("easy", "normal", "hard", "endless"):
            rows = conn.execute(
                """
                SELECT id, player_name, score, level_reached, difficulty, ship_class, game_id, created_at
                FROM scores
                WHERE difficulty = ?
                ORDER BY score DESC, created_at ASC
                LIMIT ?
                """,
                (difficulty, limit)
            ).fetchall()
        else:
            rows = conn.execute(
                """
                SELECT id, player_name, score, level_reached, difficulty, ship_class, game_id, created_at
                FROM scores
                ORDER BY score DESC, created_at ASC
                LIMIT ?
                """,
                (limit,)
            ).fetchall()

    leaderboard = [
        {
            "rank": i + 1,
            "player_name": row["player_name"],
            "game_id": row["game_id"],
            "score": row["score"],
            "level_reached": row["level_reached"],
            "difficulty": row["difficulty"],
            "ship_class": row["ship_class"] or "pushpaka",
            "created_at": row["created_at"],
        }
        for i, row in enumerate(rows)
    ]

    return jsonify({
        "count": len(leaderboard),
        "leaderboard": leaderboard
    })


@app.route("/scores/stats", methods=["GET"])
def get_stats():
    with get_db() as conn:
        total_games = conn.execute("SELECT COUNT(*) FROM scores").fetchone()[0]
        total_players = conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]
        max_score = conn.execute("SELECT MAX(score) FROM scores").fetchone()[0] or 0
        avg_score = conn.execute("SELECT AVG(score) FROM scores").fetchone()[0] or 0

    logger.info("Global stats queried: total_games=%s, max_score=%s", total_games, max_score)
    return jsonify({
        "total_games_submitted": total_games,
        "highest_score": max_score,
        "average_score": round(avg_score, 1),
        "registered_players": total_players,
    })


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    print(f"Starting Vimana Wars Leaderboard Server on port {port}...")
    app.run(host="0.0.0.0", port=port, debug=False)
