"""
game/entities/ship_classes.py
Vimana Ship Class definitions with distinct archetypes, stats, weapons, and special traits.
"""

SHIP_CLASSES = {
    "pushpaka": {
        "id": "pushpaka",
        "name": "Pushpaka Mk-I",
        "subtitle": "Celestial Balanced Cruiser",
        "hp": 100,
        "speed": 5.0,
        "fire_rate": 0.15,
        "bullet_damage": 25,
        "dash_cooldown": 2.2,
        "color": (210, 225, 255),
        "accent": (255, 215, 60),
        "sprite": "pushpaka.png",
        "unlock_wave": 0,
        "desc": "The legendary flying chariot of kings and gods. A balanced, dependable vessel favored by pilots who value steady endurance across a full campaign.",
    },
    "tripura": {
        "id": "tripura",
        "name": "Tripura Destroyer",
        "subtitle": "Heavy Armored Fortress",
        "hp": 160,
        "speed": 3.8,
        "fire_rate": 0.24,
        "bullet_damage": 48,
        "dash_cooldown": 3.0,
        "color": (255, 140, 60),
        "accent": (220, 60, 40),
        "sprite": "tripura.png",
        "unlock_wave": 0,
        "desc": "Named for the myth of the three destroyed cities. Heavy, armored, and built to withstand direct cosmic fire and answer with devastating railgun volleys.",
    },
    "garuda": {
        "id": "garuda",
        "name": "Garuda Interceptor",
        "subtitle": "High-Speed Void Striker",
        "hp": 75,
        "speed": 6.8,
        "fire_rate": 0.11,
        "bullet_damage": 18,
        "dash_cooldown": 1.4,
        "color": (120, 240, 255),
        "accent": (50, 255, 180),
        "sprite": "garuda.png",
        "unlock_wave": 0,
        "desc": "Named for Vishnu's eagle, the fastest creature in the heavens. Trades survivability for supreme agility, rapid needle blasters, and twin-burst dashes.",
    },
    "vajra": {
        "id": "vajra", "name": "Vajra Spear", "subtitle": "Lightning Lance",
        "hp": 110, "speed": 5.5, "fire_rate": 0.13, "bullet_damage": 30,
        "dash_cooldown": 1.8, "color": (255, 235, 90), "accent": (80, 180, 255),
        "sprite": "vajra.png", "unlock_wave": 5,
        "desc": "A focused lightning spear that rewards aggressive forward pressure and precise dashes.",
    },
    "naga": {
        "id": "naga", "name": "Naga Coil", "subtitle": "Serpentine Control Ship",
        "hp": 130, "speed": 4.5, "fire_rate": 0.18, "bullet_damage": 38,
        "dash_cooldown": 2.4, "color": (100, 230, 180), "accent": (40, 160, 150),
        "sprite": "naga.png", "unlock_wave": 8,
        "desc": "A resilient control craft with a steady cannon and enough armor to hold the center line.",
    },
    "agneyastra": {
        "id": "agneyastra", "name": "Agneyastra", "subtitle": "Solar Burst Frigate",
        "hp": 90, "speed": 5.8, "fire_rate": 0.10, "bullet_damage": 24,
        "dash_cooldown": 1.8, "color": (255, 130, 50), "accent": (255, 60, 30),
        "sprite": "agneyastra.png", "unlock_wave": 10,
        "desc": "Fast-firing solar artillery built for clearing dense waves before they surround you.",
    },
    "soma": {
        "id": "soma", "name": "Soma Ark", "subtitle": "Restorative Moon Cruiser",
        "hp": 115, "speed": 5.2, "fire_rate": 0.14, "bullet_damage": 32,
        "dash_cooldown": 2.0, "color": (150, 210, 255), "accent": (180, 120, 255),
        "sprite": "soma.png", "unlock_wave": 13,
        "desc": "A calm, adaptable cruiser with forgiving health and balanced astral weapon systems.",
    },
    "kubera": {
        "id": "kubera", "name": "Kubera Galleon", "subtitle": "Treasure-Hull Dreadnought",
        "hp": 190, "speed": 3.4, "fire_rate": 0.30, "bullet_damage": 65,
        "dash_cooldown": 3.4, "color": (255, 190, 70), "accent": (220, 120, 30),
        "sprite": "kubera.png", "unlock_wave": 15,
        "desc": "A slow fortress with devastating volleys, made for surviving the hardest late-game formations.",
    },
    "surya": {
        "id": "surya", "name": "Surya Flare", "subtitle": "Dawnstrike Interceptor",
        "hp": 85, "speed": 7.2, "fire_rate": 0.09, "bullet_damage": 20,
        "dash_cooldown": 1.2, "color": (255, 220, 80), "accent": (255, 110, 30),
        "sprite": "surya.png", "unlock_wave": 20,
        "desc": "The ultimate speed craft: fragile, radiant, and brutally effective in expert hands.",
    },
}
