"""
game/entities/ship_classes.py
Vimana Ship Class definitions with distinct archetypes, stats, weapons, and special traits.
Follows the authoritative Vimana Wars specification.
"""

SHIP_CLASSES = {
    "pushpaka": {
        "id": "pushpaka",
        "name": "Pushpaka Mk-I",
        "subtitle": "Celestial Carrier",
        "hp": 100,
        "speed": 5.0,
        "fire_rate": 0.15,
        "bullet_damage": 25,
        "dash_cooldown": 2.2,
        "astra_power": 75,
        "weapon": "Brahmastra Cannon",
        "ability": "Divine Barrier",
        "color": (210, 225, 255),
        "accent": (233, 196, 0),
        "sprite": "pushpaka.png",
        "unlock_wave": 0,
        "desc": "The legendary flying chariot of kings and gods gifted by Vishwakarma. A balanced, enduring flagship built for sustained campaigns across all celestial realms.",
    },
    "tripura": {
        "id": "tripura",
        "name": "Tripura Destroyer",
        "subtitle": "Siege Platform",
        "hp": 160,
        "speed": 3.8,
        "fire_rate": 0.24,
        "bullet_damage": 48,
        "dash_cooldown": 3.0,
        "astra_power": 90,
        "weapon": "Triple Agni Mortars",
        "ability": "Triple Convergence",
        "color": (255, 140, 60),
        "accent": (255, 107, 114),
        "sprite": "tripura.png",
        "unlock_wave": 0,
        "desc": "Replicates the three flying fortresses annihilated by Shiva. Unmatched frontal armor and devastating sustained fire built to break Asura dreadnought lines.",
    },
    "garuda": {
        "id": "garuda",
        "name": "Garuda Interceptor",
        "subtitle": "Aerial Assault",
        "hp": 75,
        "speed": 6.8,
        "fire_rate": 0.11,
        "bullet_damage": 18,
        "dash_cooldown": 1.4,
        "astra_power": 80,
        "weapon": "Solar Lance Array",
        "ability": "Gale Dive",
        "color": (120, 240, 255),
        "accent": (116, 245, 255),
        "sprite": "garuda.png",
        "unlock_wave": 0,
        "desc": "Modeled after the divine eagle of Vishnu. Trades durability for supreme velocity and piercing solar bolts that dissolve enemy formations before return fire.",
    },
    "vajra": {
        "id": "vajra",
        "name": "Vajra Spear",
        "subtitle": "Storm Striker",
        "hp": 110,
        "speed": 5.5,
        "fire_rate": 0.13,
        "bullet_damage": 30,
        "dash_cooldown": 1.8,
        "astra_power": 85,
        "weapon": "Thunderbolt Cannon",
        "ability": "Storm Cascade",
        "color": (255, 235, 90),
        "accent": (120, 220, 255),
        "sprite": "vajra.png",
        "unlock_wave": 5,
        "desc": "Forged from the sacrifice of Sage Dadhichi. Indra's own lightning scaled for void dogfights, rewarding forward momentum with chaining electrical arcs.",
    },
    "naga": {
        "id": "naga",
        "name": "Naga Coil",
        "subtitle": "Venom Stalker",
        "hp": 130,
        "speed": 4.5,
        "fire_rate": 0.18,
        "bullet_damage": 38,
        "dash_cooldown": 2.4,
        "astra_power": 70,
        "weapon": "Venom Torpedoes",
        "ability": "Serpent Coil",
        "color": (100, 230, 180),
        "accent": (100, 255, 180),
        "sprite": "naga.png",
        "unlock_wave": 8,
        "desc": "Engineered from the scales of the primordial serpent Vasuki. Toxic astral payload systems erode enemy shields and hold critical tactical corridors.",
    },
    "agneyastra": {
        "id": "agneyastra",
        "name": "Agneyastra",
        "subtitle": "Solar Burst Frigate",
        "hp": 90,
        "speed": 5.8,
        "fire_rate": 0.10,
        "bullet_damage": 24,
        "dash_cooldown": 1.8,
        "astra_power": 88,
        "weapon": "Solar Burst Flak",
        "ability": "Prominence Surge",
        "color": (255, 130, 50),
        "accent": (255, 120, 30),
        "sprite": "agneyastra.png",
        "unlock_wave": 10,
        "desc": "Rapid-firing solar flak built to clear dense Asura swarms before they encircle the player, leaving trails of superheated cosmic plasma.",
    },
    "soma": {
        "id": "soma",
        "name": "Soma Ark",
        "subtitle": "Support Carrier",
        "hp": 115,
        "speed": 5.2,
        "fire_rate": 0.14,
        "bullet_damage": 32,
        "dash_cooldown": 2.0,
        "astra_power": 92,
        "weapon": "Amrita Projector",
        "ability": "Lunar Renewal",
        "color": (150, 210, 255),
        "accent": (170, 80, 255),
        "sprite": "soma.png",
        "unlock_wave": 13,
        "desc": "Named for the nectar of immortality and the moon deity. Equipped with regenerative Amrita field capacitors and balanced astral defenses.",
    },
    "kubera": {
        "id": "kubera",
        "name": "Kubera Galleon",
        "subtitle": "Heavy Fortress",
        "hp": 190,
        "speed": 3.4,
        "fire_rate": 0.30,
        "bullet_damage": 65,
        "dash_cooldown": 3.4,
        "astra_power": 95,
        "weapon": "Ratna Siege Gun",
        "ability": "Fortress Mode",
        "color": (255, 190, 70),
        "accent": (233, 196, 0),
        "sprite": "kubera.png",
        "unlock_wave": 15,
        "desc": "The celestial treasury rendered as an orbital fortress. Heavy gold-plated hull plating with overwhelming single-volley kinetic yield.",
    },
    "surya": {
        "id": "surya",
        "name": "Surya Flare",
        "subtitle": "Solar Radiant",
        "hp": 85,
        "speed": 7.2,
        "fire_rate": 0.09,
        "bullet_damage": 20,
        "dash_cooldown": 1.2,
        "astra_power": 98,
        "weapon": "Solar Flare Burst",
        "ability": "Radiance Surge",
        "color": (255, 220, 80),
        "accent": (255, 215, 0),
        "sprite": "surya.png",
        "unlock_wave": 20,
        "desc": "The ultimate high-velocity strike craft: fragile, radiant, and delivering devastating point-blank bursts in the hands of master pilots.",
    },
}
